### ISSUE TITLE
[FEATURE] Generate Java JKS store from vault certificate

### ISSUE THREAD

**Issue by mstavrev** [SparebankenVest/azure-key-vault-to-kubernetes#152]
Hello,

**Is your feature request related to a problem? Please describe.**
This is a feature request.
I am trying to automate the deployment of an application, which terminate TLS connections itself. The TLS listener and client certificate validation require JKS files to operate. The application is capable to detect changes on the JKS stores and reload the certificate(s) automatically, without being restarted. I am looking for a way to generate the JKS files from certificate(s) kept on AKV.

**Describe the solution you'd like**
Ideally, we can have a simple pod that works as a sidecar along the main application pod. The sidecar can use the config map generated by akv2k8s to run the java-specific JKS creation tool and write the file to a shared mount between the app and the sidecar pod.

**Describe alternatives you've considered**
Right now I am generating the JKS manually and add them under the main app's container file system.

Most likely what I am requesting can be implemented with other readily available tools, pardon me if that's the case. Hints would be appreciated.

Best Regards
Marin

**Comment by 181192** [comment]
Hello @mstavrev,

JKS support is a bit out of scope for akv2k8s, but we have multiple options that could maybe work for you.

- Using the multi-value feature, makes it possible to have multiple values sync to the same Kubernetes secret https://akv2k8s.io/tutorials/sync/4-multi-key-value-secret/ 
- There are some support for using transformations on the content like base64 encoding/decoding https://akv2k8s.io/reference/azure-key-vault-secret/#output-transformation
- Support for outputting configmaps instead of secrets is an open issue on #18 

Not sure if this is an answer to you question, feel free to describe the problem further.

**Comment by mstavrev** [comment]
Hello,

The second option (output transformation) seems a good approach.
Is it possible to add new type of custom transformation that can spawn a temporary container providing it the certificate file for processing? 
I believe I can setup a container with the necessary JKS creation tools that can then store it under a specific configmap.

**Comment by torresdal** [comment]
We're currently reviewing all old and new feature requests, and it's decided that his feature will not be added to akv2k8s.
