### ISSUE TITLE
[Question] how to rebuild the controller image

### ISSUE THREAD

**Issue by tgotzsche** [SparebankenVest/azure-key-vault-to-kubernetes#208]
**Your question**
We would like the make some changes to how the controller works (change the sync interval). 
But how can we build the spvest/azure-keyvault-controller image?

**To Reproduce**
cd azure-key-vault-to-kubernetes/images/controller
docker build - < Dockerfile 

**Logs**
------
 => [stage-1 2/3] RUN apk update && apk add --no-cache     ca-certificates     iptables     && update-ca-certificates                                                                       7.0s 
 => [build 2/1] RUN mkdir -p /go/src/${PACKAGE}                                                                                                                                             0.2s 
 => [build 3/1] WORKDIR /go/src/                                                                                                                                                            0.0s 
 => [build 4/1] COPY . /go/src/                                                                                                                                                             0.0s 
 => ERROR [build 5/1] RUN CGO_ENABLED=0 go install ${VCS_PROJECT_PATH}                                                                                                                      0.2s

 > [build 5/1] RUN CGO_ENABLED=0 go install ${VCS_PROJECT_PATH}:
#12 0.201 can't load package: package .: no Go files in /go/src

**Additional context**
Add any other context about the question here.

**Comment by kristeey** [comment]
As I have understood, building the akv2k8s images is done using the `Makefile` in the root directory. The `Makefile` consists of a lot of Makefile rules which you can use to build, pull, push and tag images using docker commands. If we inspect the `Makefile` we see that the rule for building the azure-keyvault-controller is specified in [code line 231-241](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/f6e0914a14bd1df6b0a200f6994668e34beb582a/Makefile#L231-L241) as follows:
```
.PHONY: image-controller
image-controller:
	DOCKER_BUILDKIT=1 docker build \
		--progress=plain \
		--target controller \
		--build-arg BUILD_SUB_TARGET="-controller" \
		--build-arg PACKAGE=$(PACKAGE) \
		--build-arg VCS_REF=$(DOCKER_INTERNAL_TAG) \
		--build-arg BUILD_DATE=$(BUILD_DATE) \
		--build-arg VCS_URL=$(VCS_URL) \
		-t $(DOCKER_INTERNAL_REG)/$(DOCKER_CONTROLLER_IMAGE):$(DOCKER_INTERNAL_TAG) .
```
Hence, from your terminal you run `make image-controller` in order to run the `docker build . ` command specified in this rule. The docker command uses the `Dockerfile` in the root directory and builds only the target named [`controller` stage](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/f6e0914a14bd1df6b0a200f6994668e34beb582a/Dockerfile#L38-L56). The `controller` stage copies the artifacts from the [`builder` stage](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/f6e0914a14bd1df6b0a200f6994668e34beb582a/Dockerfile#L5-L16). The `builder` stage downloads go modules (line 15) and runs a `make build-controller` command which activates the [`build-controller` rule](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/f6e0914a14bd1df6b0a200f6994668e34beb582a/Makefile#L196-L198) in the makefile, that subsequently activates a `go build` command in the [`bin/%` rule ](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/f6e0914a14bd1df6b0a200f6994668e34beb582a/Makefile#L169) which will generate the go artifacts (executable) named `bin/$(PROJECT_NAME)/$(CONTROLLER_BINARY_NAME)` which in this case is `bin/azure-key-vault-to-kubernetes/azure-keyvault-controller`. 

By gathering only the necessary stuff to build the azure-keyvault-controller image you can make your own Makefile and Docker file (in the root directory) with your own modifications, e.g.: 
```
# CUSTOM MAKEFILE

ORG_PATH=github.com/SparebankenVest
PROJECT_NAME := azure-key-vault-to-kubernetes
PACKAGE=$(ORG_PATH)/$(PROJECT_NAME)
DOCKER_CONTROLLER_IMAGE=azure-keyvault-controller
DOCKER_INTERNAL_TAG := $(shell git rev-parse --short HEAD)
COMPONENT_VAR=$(PACKAGE)/pkg/akv2k8s.Component
GIT_VAR=$(PACKAGE)/pkg/akv2k8s.GitCommit
BUILD_DATE_VAR := $(PACKAGE)/pkg/akv2k8s.BuildDate
BUILD_DATE := $(shell date -u +"%Y-%m-%dT%H:%M:%SZ")
CONTROLLER_BINARY_NAME=azure-keyvault-controller

TAG=
GOOS ?= linux

GO_BUILD_OPTIONS := --tags "netgo osusergo" -ldflags "-s -X $(COMPONENT_VAR)=$(COMPONENT) -X $(GIT_VAR)=$(GIT_TAG) -X $(BUILD_DATE_VAR)=$(BUILD_DATE) -extldflags '-static'"

bin/%:
	GOOS=$(GOOS) GOARCH=amd64 go build $(GO_BUILD_OPTIONS) -o "$(@)" "$(PKG_NAME)"

.PHONY: clean-controller
clean-controller:
	rm -rf bin/$(PROJECT_NAME)/$(CONTROLLER_BINARY_NAME)

.PHONY: build-controller
build-controller: clean-controller
	CGO_ENABLED=0 COMPONENT=controller PKG_NAME=$(PACKAGE)/cmd/$(CONTROLLER_BINARY_NAME) $(MAKE) bin/$(PROJECT_NAME)/$(CONTROLLER_BINARY_NAME)

.PHONY: image-controller
image-controller:
	DOCKER_BUILDKIT=1 docker build \
		--progress=plain \
		--target controller \
		--build-arg BUILD_SUB_TARGET="-controller" \
		--build-arg PACKAGE=$(PACKAGE) \
		--build-arg VCS_REF=$(DOCKER_INTERNAL_TAG) \
		-t my-custom-image:my-tag .
```
``` 
# CUSTOM DOCKERFILE

ARG BASEIMAGE=gcr.io/distroless/static:nonroot
ARG BASE_ALPINE=alpine:3.14.0
ARG GO_VERSION=1.16.5

# -------
# Builder
# -------
FROM golang:${GO_VERSION} AS builder
ARG PACKAGE
ARG VCS_REF=noref
ARG BUILD_SUB_TARGET

WORKDIR /go/src/${PACKAGE}
ADD . .
RUN go mod download
RUN GIT_TAG=${VCS_REF} make build${BUILD_SUB_TARGET}
# ----------
# Controller
# ----------
FROM $BASE_ALPINE AS controller
COPY --from=builder /go/src/github.com/SparebankenVest/azure-key-vault-to-kubernetes/bin/azure-key-vault-to-kubernetes/azure-keyvault-controller /usr/local/bin/
ENV DEBUG false
ENTRYPOINT ["/usr/local/bin/azure-keyvault-controller"]
```
... or just use the existing `Makefile` and `Dockerfile`.
