### ISSUE TITLE
[Question] How to configure resource request limits with env injector

### ISSUE THREAD

**Issue by sareykaj** [SparebankenVest/azure-key-vault-to-kubernetes#210]
**Note: Make sure to check out known issues (https://github.com/sparebankenvest/azure-key-vault-to-kubernetes#known-issues) before submitting**

**Your question**
I have tried to configure an env-injector for a KeyVault Secret. We have resource quotas configured for the namespace where the pod receives the injected secret. When depoying, an kubernetes error event from the replicaset-controller is emitted although we have quota definitions for the pod and the istio sidecar:

Error creating: pods "..." is forbidden: failed quota: resources: must specify limits.cpu,limits.memory,requests.cpu,requests.memory

Question: from my unterstanding the env-injector is not a sidecar but it manipulates the original container. So why do I get this error and what can I do about.

**Comment by kristeey** [comment]
This is most likely because the env-injector webhook mutates the pod and adds a init-container to the pod which is ran before the other containers in the pod. This init-container also need resource quotas assigned to it. There is at this point no way to assigning using the helm chart. In order to work around it you could use [`LimitRange` objects](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/) to configure default resource quotas to the namespace.
