### ISSUE TITLE
[FEATURE] FileInjector option to mount KV secrets into a volume

### ISSUE THREAD

**Issue by elliottnichols** [SparebankenVest/azure-key-vault-to-kubernetes#61]
Problem: Lazy app developers have a habit of dumping all env vars to logs. Env vars are also exposed in clear text in some UIs (Azure Log analytics portal for example) which is not desirable with secrets.

Solution: Much like the EnvInjector, support a FileInjector that will inject secrets using the init-container into an in-memory volume for the pod.

**Comment by ChaosGramer** [comment]
Hey, 

We have similar issues with our dev teams. I already thought about an fileInjector and it would be possible, but it is less secure as the envInjector, because you would be able to read the passwords from any process running in the container. So far only the container startup process is capable of reading the password. 

@torresdal What do you think is this something we should implement?

**Comment by torresdal** [comment]
Technically this is not a problem to implement, but the problem you describe @elliottnichols is already covered by the env-injector today. It also nicely adhere to the [12-factor app principle for configuration](https://12factor.net/config). As for the lazy dev aspect, that is not lazy but reckless and unprofessional (and yes, you can quote me on that). 

Don’t see what the file-injector would add except exposition secrets in files within the pod... Unless there other scenarios where a file-injector would make sense, I have a hard time finding a good argument for this, from a security standpoint.

**Comment by mozts2005** [comment]
@elliottnichols Why not use the Azure Key Vault Provider for Secrets Store CSI Driver?
https://github.com/Azure/secrets-store-csi-driver-provider-azure

**Comment by torresdal** [comment]
Closing as @elliottnichols has given good alternative
