### ISSUE TITLE
[FEATURE] Add an option to synchronyze secrets containing certificates as K8S tls secret

### ISSUE THREAD

**Issue by deuch** [SparebankenVest/azure-key-vault-to-kubernetes#70]
**Is your feature request related to a problem?
In Azure, App Service Certificate store the generated certificates as a secret and not a certificate.
With the Controller, you can synchronize Key Vault certificates to K8S TLS secret. But if the source is a secret, you can not choose kubernetes.io/tls as output.
Certificates provided by App Services Certificates provide an auto-renew feature, so it will be very handy to have the Controller to be able to check the secret once per day and modify the kubernetes.io/tls secret if the certificates has been renewed.
With this system we can ensure that both certificates (the one used by the ingress, and the one used by the application, retrieved with env-injector or flexvolume or other tools) will be synchronized.
We want to avoid as much as possible to use kubernetes secrets, but for ingress we have no choice for the moment. For applicative container, the certificates is retrieved during each container start to be sure to have the latest one (we deploy at least one time per week, so the certificate will always be ok, before it’s renew 30 days before the expiry date)

We would like to avoid incident with ingress certificates that need to be updated manually ... 

**Describe the solution you'd like**
Add an option as input type like certificate-as-a-secret and provide the output type as kubernetes.io/tls

**Describe alternatives you've considered**
Manually update the ingress certificate. Copy secrets to certificates in Key Vault with batches (not great ...)

**Comment by torresdal** [comment]
Hi @deuch,

In order to export a certificate as Kubernetes TLS secret we need both the public and private key. Are you saying both these are stored as Secrets in AKV? Normally, the private key is stored as Secret and the public key as Certificate.

What akv2k8s does is first get the certificate (public key) from AKV, then if the metadata of the Certificate specifies the private key as exportable, it will also get the private key by getting the  Secret with the same name as the certificate (this is by convention in AKV).

To see the details, the code is here: https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/3c51c61892474379ccb243337159626f9db2c7b6/pkg/azurekeyvault/client/azure_keyvault_service.go#L101

Specifically, if key is exportable, we get the secret: https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/3c51c61892474379ccb243337159626f9db2c7b6/pkg/azurekeyvault/client/azure_keyvault_service.go#L121

**Comment by deuch** [comment]
Hello,

Yes in AKV, the certificate is stored as a PFX certificate with public and private key in the same bundle.

With App Service Certificate, there is nothing in AKV Certificates, only in Secrets.
It is stored as application/x-pkcs12 kind. If you check the secret in KV, you have a button « Download as a certificate ». You can download it, convert it with openssl (for eg) and retrieve private and public key as pem if you want.

**Comment by deuch** [comment]
Hello any news about this feature that will be very usefull for all users of App Service Certificate ?

**Comment by deuch** [comment]
It seems to exist for env-injector : extract a PFX from a secret. Can you do the same for the Controller ?

**Comment by torresdal** [comment]
Looking through all feature requests now and in order to support this I think I need to rely on a pull-request or a detailed example with code. Happy to review and help. As you mentioned @deuch the injector support this (was not trivial).

**Comment by kristeey** [comment]
Closing as this functionality exists in controller version >1.3. See documentation for example [tutorial with self signed certificate](https://akv2k8s.io/tutorials/sync/9-certificate-as-AKV-secret/).
