### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by prabhavgupta** [SparebankenVest/azure-key-vault-to-kubernetes#97]
**Note: Make sure to check out known issues (https://github.com/sparebankenvest/azure-key-vault-to-kubernetes#known-issues) before submitting**

**Your question**
Is this project in active development? I don't see any recent commits as well as replies on the issues raised.

**Comment by vidarw** [comment]
Yes, the project is actively maintained and incoming questions and pull requests are reviewed periodically. Key developers and maintainers are currently on summer vacation.

Commits from our organization will mainly focus on bugfixes since the software is currently delivering a stable feature set within it's scope. However feature suggestions, improvements and bugfixes from the community are, as in any open source project, always welcome.
